eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
  
microservice:
  paymentService: http://payment-service/payment/doPayment
  orderService: http://order-service/order/bookOrder
